### ISSUE TITLE
和cesium  1.108 一起使用报错

### ISSUE THREAD

**Issue by yuntian001** [postor/cesiumjs-heat#10]
HS {name: 'RuntimeError', message: 'Failed to load image data:,: The source image could not be decoded.', stack: 'Error\n    at new HS (http://localhost:8003/Cesium1…//localhost:8003/Cesium108/Cesium.js:10392:28189)'}

**Comment by postor** [comment]
pls have a try with version [1.0.2](https://www.npmjs.com/package/cesiumjs-heat/v/1.0.2)
