### ISSUE TITLE
How to get layer outside?

### ISSUE THREAD

**Issue by qdxkrs** [postor/cesiumjs-heat#2]
thanks for your work on heatmap.hower,how to get the layer outside,this is one very common case especially for controller heatmap layer.

**Comment by postor** [comment]
Do you mean to destory the heat layer? see cod in https://github.com/postor/cesiumjs-heat#usage usage secction `heat.destory()`

**Comment by postor** [comment]
In case you want to use `heat` instance in another module, just export it

**Comment by postor** [comment]
I close it for now, you can still comment in this thread or open another issue

**Comment by postor** [comment]
Ah for the layer, it is tricky, you can get it by `heat.layer` but it changes when camera move, so I'm not exposing it
