### ISSUE TITLE
extrudedHeight

### ISSUE THREAD

**Issue by Desever** [postor/cesiumjs-heat#3]
请问一下如何设置extrudedHeight呢

**Comment by postor** [comment]
这个热力图实际是Cesium.SingleTileImageryProvider，要用extrudedHeight做立体效果么，不太合适吧，如果你想要长出地面的图表还是考虑自己绘制或者基于Cesium矢量的图表库

**Comment by Desever** [comment]
好的，谢谢您的解答，最后用canvas自己绘制，然后铺上去了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "postor/cesiumjs-heat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 中午11:07
收件人:&nbsp;"postor/cesiumjs-heat"<cesiumjs-heat@noreply.github.com&gt;;
抄送:&nbsp;"--Deserve"<1446514143@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [postor/cesiumjs-heat] extrudedHeight (#3)





 
Closed #3.
