### ISSUE TITLE
现在默认显示台湾数据， 如果要展示其它地区数据需要修改哪些东西？大佬请指教，在线等挺急的

### ISSUE THREAD

**Issue by webxiuer** [postor/cesiumjs-heat#4]

**Comment by postor** [comment]
你这要求太高了，有文档，有示例代码，自己不能看看改改试试么

**Comment by webxiuer** [comment]
canvas画布如果太大覆盖整个亚洲的话，为啥热力图出不来，会特别卡

**Comment by postor** [comment]
> canvas画布如果太大覆盖整个亚洲的话，为啥热力图出不来，会特别卡

canvas是像素更新的，不管什么应用弄个大canvas都能把它拖垮，所以推荐只设置bbox，默认的画布大小已经是我保证性能同时尽量高分辨率了，当然你有耐心可以自己逐步放大画布，卡了你就要考虑调小一点了


你要显示亚洲的，可以先只用前两个参数（viewer,data），其他的不填保持默认，等你的数据能显示出来，这个时候图会比较糊，因为你把热力显示到了整个地球，但至少验证了你的数据没问题，然后再追加第三个参数bbox，把热力图渲染范围限制到亚洲，热力图就会清晰些

**Comment by webxiuer** [comment]
画布如果不动的话，即使数据是全亚洲的因该也显示不出来吧，顺便大佬可以加个V吗，以后这方面还请大佬多多指点。 +V：18731357665，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 上午9:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [postor/cesiumjs-heat] 现在默认显示台湾数据， 如果要展示其它地区数据需要修改哪些东西？大佬请指教，在线等挺急的 (#4)





  
canvas画布如果太大覆盖整个亚洲的话，为啥热力图出不来，会特别卡
  
canvas是像素更新的，不管什么应用弄个大canvas都能把它拖垮，所以推荐只设置bbox，默认的画布大小已经是我保证性能同时尽量高分辨率了，当然你有耐心可以自己逐步放大画布，卡了你就要考虑调小一点了
 
你要显示亚洲的，可以先只用前两个参数（viewer,data），其他的不填保持默认，等你的数据能显示出来，这个时候图会比较糊，因为你把热力显示到了整个地球，但至少验证了你的数据没问题，然后再追加第三个参数bbox，把热力图渲染范围限制到亚洲，热力图就会清晰些

**Comment by postor** [comment]
你加我吧，微信 postor
